/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author ldani
 */
public class VistaAdminUsuario extends javax.swing.JFrame {

   private ControladorAdminUsuario miControl;
   private Modelo miModelo;

   
    public VistaAdminUsuario(Modelo m) {
        miModelo = m;
        initComponents();
        this.setLocationRelativeTo(null);        
        capturareventos();
    }

    public ControladorAdminUsuario getMiControl() {
        if (miControl == null) {
            miControl = new ControladorAdminUsuario(this);
        }
        return miControl;
    }

    public void capturareventos() {
       getBtnVolver().addActionListener(getMiControl());
       getBtnCrearUsuario().addActionListener(getMiControl());              
    }

    public Modelo getMiModelo() {
        return miModelo;
    }

    public JButton getBtnCrearUsuario() {
        return btnCrearUsuario;
    }


    public JButton getBtnVolver() {
        return btnVolver;
    } 

    
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        btnCrearUsuario = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCrearUsuario.setText("Crear Usuario");
        btnCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUsuarioActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btnVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btnCrearUsuario)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(btnCrearUsuario)
                .addGap(65, 65, 65)
                .addComponent(btnVolver)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearUsuarioActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearUsuario;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables
}
